sudo: required
services:
  - docker

before_install:
  - docker build -t anlakngs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anlakngs/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2" 
  app: "docker-react"
  env: "Dockerreact-env"   
  bucket_name: "elasticbeanstalk-us-east-2-069202033898"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



